name: ezvocab
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  go_router: ^16.1.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  settings_ui: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
