// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDce5VCAulP4EjhA4PxNkkHyttdH1K1eOg',
    appId: '1:1061483004772:web:7313a684d7e35d621bb071',
    messagingSenderId: '1061483004772',
    projectId: 'ezvocab-392d4',
    authDomain: 'ezvocab-392d4.firebaseapp.com',
    storageBucket: 'ezvocab-392d4.firebasestorage.app',
    measurementId: 'G-E0T381CRF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA91TeJ2Z2jglGR1I1nkDWMbxxNS53Yixo',
    appId: '1:1061483004772:android:c11bb37fdef816291bb071',
    messagingSenderId: '1061483004772',
    projectId: 'ezvocab-392d4',
    storageBucket: 'ezvocab-392d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACIDMmMNFq9JlHtJqSmSoarJ6ymZ9zT3k',
    appId: '1:1061483004772:ios:6e930b5ee1aac2651bb071',
    messagingSenderId: '1061483004772',
    projectId: 'ezvocab-392d4',
    storageBucket: 'ezvocab-392d4.firebasestorage.app',
    iosBundleId: 'com.example.ezvocab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACIDMmMNFq9JlHtJqSmSoarJ6ymZ9zT3k',
    appId: '1:1061483004772:ios:6e930b5ee1aac2651bb071',
    messagingSenderId: '1061483004772',
    projectId: 'ezvocab-392d4',
    storageBucket: 'ezvocab-392d4.firebasestorage.app',
    iosBundleId: 'com.example.ezvocab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDce5VCAulP4EjhA4PxNkkHyttdH1K1eOg',
    appId: '1:1061483004772:web:c09a8e637be8274f1bb071',
    messagingSenderId: '1061483004772',
    projectId: 'ezvocab-392d4',
    authDomain: 'ezvocab-392d4.firebaseapp.com',
    storageBucket: 'ezvocab-392d4.firebasestorage.app',
    measurementId: 'G-NNTPZTL6KF',
  );
}
